### ISSUE TITLE
Availability in German app store

### ISSUE THREAD

**Issue by rm-rf-home** [vermont42/RaceRunner#4]
I would love to use your app but it is not available in the German app store. Is there a particular reason for this? Are there plans to release the app in Germany?

**Comment by vermont42** [comment]
Danke für Ihr Interesse! I would not release RaceRunner to non-English-speaking App Stores without internationalizing and localizing it. RaceRunner is a side project, so the time I can spend on it is limited. My priority for it now is adding Siri support, not internationalizing or localizing.

The good news is that you can clone the repo and use Xcode 9.3 to deploy RaceRunner to your iPhone. The only thing you need to do is obtain API keys for Google Maps, Dark Sky, and PubNub. You don't need to `pod install` because I am saving dependencies in GitHub.

All this said, if you were willing to translate all the text in RaceRunner and its App Store description to German, I would be willing to internationalize it.

**Comment by rm-rf-home** [comment]
Hi Josh, thanks for your answer. Is there a central place in the source code with all the text, so I can have a look at it? Are you willing to use something like crowdin.com or is this too much efford for your side project?

**Comment by vermont42** [comment]
@rm-rf-home No, strings are not centralized. They are at the tops of class definitions.

As I think about it, I am unwilling to internationalize/localize this app. There is just not enough potential benefit.

**Comment by rbozan** [comment]
I would gladly use this app without internationalization. I have my phone in English but I’m Dutch, but unfortunately this app is also unavailable in The Netherlands. Building the app myself is also not possible as I don’t have a Mac.

**Comment by vermont42** [comment]
@rbozan If I may ask, how did you find RaceRunner, and what about the app interests you? It is the least popular of my three apps, but it is the one I use most. Certain features like shoe-life tracking and automatic stopping after a certain distance are just not available in competing apps.

I am not surprised to encounter an English-fluent Netherlander. 😅Out of respect for the [two or three](https://en.wikipedia.org/wiki/English_in_the_Netherlands) people in your country who do _not_ speak English, I would not release an app there without localizing it. If I do internationalize the app, I will offer you the task of translating the `String`s to [Netherlandish](https://upload.wikimedia.org/wikipedia/commons/5/55/Nl-Scheveningen.ogg). In the interim, I recommend that you create an Apple ID for the US App Store and use that to install the app, as described [here](https://www.makeuseof.com/tag/dont-switch-international-itunes-media-app-store-youve-read/).

FWIW, my [other](https://itunes.apple.com/us/app/immigration/id777319358) [two](https://itunes.apple.com/us/app/conjugar/id1236500467) apps are localized for Spanish and Portuguese.

**Comment by rbozan** [comment]
I found it after doing some Google searches for ‘open source run tracker app iOS’, then I found your app on https://github.com/dkhamsing/open-source-ios-apps.

To be honest I just would like a tracking app where I know that nothing bad is being done with my data, that can track how fast I’m running and nothing else. All mainstream app pretty much keeps asking if I want to buy their premium plan, and most seem to be more of a social network kind of thing, but I just want something really simple that just tracks my running and that’s it.

To be honest I don’t think I would translate the strings for you, it’s not really necessary for me to have this app (or any running app) but it would just be nice. I understand it if you wouldn’t want to put extra work in (by publishing the app in The Netherlands etcetera) if you get nothing in return, so if you don’t want to put the extra work in its all fine.

**Comment by vermont42** [comment]
Thank you for your honesty! Agreed that other run-tracking apps are aggressive about making you pay, and if they aren't, there is a question as to whether they're selling your data. Trying other apps for my market research was an unpleasant experience. 

I hope you are able to install by creating a US Apple ID. Please let me if this works. If it does, I will add a note to the readme.
